### ISSUE TITLE
Time improvement

### ISSUE THREAD

**Issue by elbae** [JulesDT/ctfWriteUps#1]
Firstly, this is great. 
This is not a real issue, but you can improve your execution time using four variable :
sum_A, sum_B, len_A, len_B instead of A and B as lists.
I know that at this point id doesn't matter but just for saying :-)
(result as string, ready to be sent)
`def find_partition(int_list,n,k):
    len_A=0; len_B=0; sum_A=0; sum_B=0
    Aret = ""; Bret = ""

```
for i in range(0,len(int_list)):
    int_list[i] += 2**n
int_list=int_list[::-1]

for nb in int_list:
    if nb == 0:
        if len_A < len_B:
            len_A+=1
            Aret+= str(-2**n)+ " "
        else:
            len_B+=1
            Bret+= str(-2**n)+ " "
    else:
        if sum_A < sum_B:
           sum_A+=(nb**k)
           len_A+=1
           Aret+=str(nb-(2**n))+ " "
        else:
           sum_B+=(nb**k)
           len_B+=1
           Bret+=str(nb-(2**n))+ " "
return (Aret)`
```

**Comment by JulesDT** [comment]
Thanks a lot for this improvement ! It is, in fact really faster ! I did not search for time improvement during the CTF, but I like this solution and will edit my Write Up !
