### ISSUE TITLE
Math?

### ISSUE THREAD

**Issue by cfossace** [JulesDT/ctfWriteUps#2]
This is not a real issue, but I couldn't figure out how to send you a direct message!

Can you explain how you knew(or the math behind) why the partitions are the same when you add (2**n) to each element in the set (and eliminate the negatives)? What was your process in figuring that out?

This is a really elegant solution thank you for posting. It's better you have it in python, because C++ would have made you use long ints or long long ints or something.

**Comment by JulesDT** [comment]
Hi cfossace !

Eliminating the negative numbers is necessary for the algorithm to work. In fact, the main part in the algorithm is the `sum_A < sum_B` part. If we are using negative numbers, if `sum_A < sum_B` then we will add a negative number to A, and then sum_A will still be less than sum_B and we will end with set A being far bigger than B :)
So as far as we are only searching for equality in term of sum and number of elements, adding the same amount to each set won't change anything.
To go further in the maths, we have a total of `2**(n+1)` elements to separate between the sets. So we will have `2**n` elements in each set, and therefore, we will add the same total to each set (add `2**(2n)` if I'm correct), and therefore not change the sum equality part.

Once we only have positive elements, we have a new starting set equal to : 
`{a | 0 <= a < (2**(n+1))-1}` and our algorithm can work properly.

In fact, to see quickly that adding these numbers changes nothing to the result, we have three key points :
- The sum of the sets must be equal. (If we searched a difference equal to an integer k for example, we should have changed k value)
- The length of each set must be the same (Therefore we add the same total to each set and keep sum equality)
- We finally keep numbers order. We're just translating :)

Hope this explains you the math behind, keep the questions coming if you have some more !

Pod
